# Generated by Django 3.0.4 on 2020-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_pojedynczawartoscwyniku_wynik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ustawienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakre1', models.FloatField()),
                ('zakre2', models.FloatField()),
                ('dokladnosc', models.IntegerField()),
                ('wielkoscPopulacji', models.IntegerField()),
                ('liczbaepok', models.IntegerField()),
                ('metodaSelekcji', models.TextField()),
                ('implementacjaKrzyzowania', models.TextField()),
                ('prawdobodobienstwoKrzyzowania', models.IntegerField()),
                ('implementacjaMutowania', models.TextField()),
                ('prawdobodobienstwoinwersji', models.IntegerField()),
                ('ileprzechodzi', models.IntegerField()),
            ],
        ),
    ]
