# Generated by Django 3.0.4 on 2020-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_ustawienia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ustawienia',
            old_name='zakre1',
            new_name='zakres1',
        ),
        migrations.RenameField(
            model_name='ustawienia',
            old_name='zakre2',
            new_name='zakres2',
        ),
        migrations.AddField(
            model_name='ustawienia',
            name='prawdobodobienstwoMutowania',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ustawienia',
            name='rodzaj_Optymalizacj',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
