# Generated by Django 3.0.4 on 2020-05-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20200522_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wynik',
            name='wyniki',
        ),
        migrations.AddField(
            model_name='wynik',
            name='wyniki',
            field=models.ManyToManyField(to='Main.PojedynczaWartoscWyniku'),
        ),
    ]
